Repository likelion-LIKIT/Front-end, pull requests merged in 2023-03, with the labels that each got.

#16 Feature/feat
  src/common/components/Modal.js
  src/common/styles/Modal.css
  src/pages/main/api/ScheduleAPI.js
  src/pages/main/components/MainCalender.js
  src/pages/main/components/MainPage.js
  src/pages/main/components/ScheduleModal.js
  src/pages/main/styles/MainCalender.css
  src/pages/main/styles/ScheduleModal.css
  src/pages/main/utils/CalenderUtils.js
  src/pages/main/utils/ExceptionUtils.js
  src/pages/main/utils/ScheduleUtils.js
Labels: enhancement

#17 Feature/feat
  public/images/carousel_left_button.png
  public/images/carousel_right_button.png
  public/images/default_image.png
  src/App.js
  src/common/components/ContentsFrame.js
  src/common/components/Title.js
  src/common/constant/Title.js
  src/common/styles/ContentsFrame.css
  src/common/styles/Title.css
  src/pages/activity/ActivityDetailPage/components/ActivityDetailPage.js
  src/pages/activity/ActivityDetailPage/styles/ActivityDetailPage.css
  src/pages/activity/ActivityPage/components/ActivityCard.js
  src/pages/activity/ActivityPage/components/ActivityFrame.js
  src/pages/activity/ActivityPage/components/ActivityPage.js
  src/pages/activity/ActivityPage/constant/activityData.js
  src/pages/activity/ActivityPage/styles/ActivityCard.css
  src/pages/activity/ActivityPage/styles/ActivityFrame.css
  src/pages/notice/NoticeDetailPage/components/NoticeDetailPage.js
  src/pages/notice/NoticeDetailPage/styles/NoticeDetailPage.css
  src/pages/notice/NoticePage/components/NoticeCard.js
  src/pages/notice/NoticePage/components/NoticePage.js
  src/pages/notice/NoticePage/constant/Notice.js
  src/pages/notice/NoticePage/constant/noticeData.js
  src/pages/notice/NoticePage/styles/NoticeCard.css
Labels: enhancement

#19 Feature/feat
  public/images/arrow_black.png
  public/images/checked_button.png
  public/images/checked_more_button.png
  public/images/delete_modal_icon.png
  src/App.js
  src/common/components/DeleteModal.js
  src/common/constant/Title.js
  src/common/styles/DeleteModal.css
  src/pages/accountBook/AccountBookPage/components/AccountBookCard.js
  src/pages/accountBook/AccountBookPage/components/AccountBookPage.js
  src/pages/accountBook/AccountBookPage/styles/AccountBookCard.css
  src/pages/accountBook/constant/accountBookData.js
  src/pages/activity/ActivityDetailPage/components/ActivityDetailPage.js
  src/pages/activity/ActivityPage/components/ActivityCard.js
  src/pages/activity/ActivityPage/components/ActivityFrame.js
  src/pages/activity/ActivityPage/styles/ActivityCard.css
  src/pages/activity/ActivityPage/styles/ActivityFrame.css
  src/pages/assignment/AssignmentPage/components/AssignmentCard.js
  src/pages/assignment/AssignmentPage/components/AssignmentPage.js
  src/pages/assignment/AssignmentPage/styles/AssignmentCard.css
  src/pages/assignment/constant/assignmentData.js
  src/pages/notice/NoticeDetailPage/components/CheckedModal.js
  src/pages/notice/NoticeDetailPage/components/NoticeDetailPage.js
  src/pages/notice/NoticeDetailPage/styles/CheckedModal.css
  src/pages/notice/NoticeDetailPage/styles/NoticeDetailPage.css
  src/pages/notice/NoticePage/constant/noticeData.js
  src/pages/notice/NoticePage/styles/NoticeCard.css
  src/pages/regulation/components/RegulationPage.js
Labels: enhancement

#20 Feature/feat
  public/images/file_icon.png
  src/App.js
  src/common/components/DeleteModal.js
  src/common/components/FileListBox.js
  src/common/components/FileUploadBtn.js
  src/common/components/FormHeader.js
  src/common/components/FormTitle.js
  src/common/components/FormWriteBox.js
  src/common/components/Navbar.js
  src/common/components/Preview.js
  src/common/components/Title.js
  src/common/constant/Form.js
  src/common/styles/FileListBox.css
  src/common/styles/FileUploadBtn.css
  src/common/styles/FormHeader.css
  src/common/styles/FormTitle.css
  src/common/styles/FormWriteBox.css
  src/common/styles/Preview.css
  src/pages/activity/ActivityPage/styles/ActivityCard.css
  src/pages/activity/ActivityPage/styles/ActivityFrame.css
  src/pages/notice/NoticeFormPage/components/NoticeFormPage.js
  src/pages/notice/NoticeFormPage/components/NotionFormModal.js
  src/pages/notice/NoticeFormPage/constant/CategoryData.js
  src/pages/notice/NoticeFormPage/styles/NoticeFormPage.css
  src/pages/notice/NoticeFormPage/styles/NotionFormModal.css
  src/pages/notice/NoticeFormPage/utils/MarkDownParser.js
Labels: enhancement

#21 Feature/feat
  src/common/styles/Layout.css
  src/pages/main/api/NoticeAPI.js
  src/pages/main/components/MainCalender.js
  src/pages/main/components/MainNotice.js
  src/pages/main/components/MainPage.js
  src/pages/main/components/MainQuick.js
  src/pages/main/styles/MainCalender.css
  src/pages/main/styles/MainNotice.css
  src/pages/main/styles/MainPage.css
  src/pages/main/styles/MainQuick.css
  src/pages/main/utils/NoticeUtils.js
Labels: enhancement

#22 Feater/feat
  public/images/LIKELION_brandsymbol.png
  public/images/basic_profile.png
  src/App.js
  src/common/constant/Title.js
  src/common/styles/Layout.css
  src/pages/introduce/IntroducePage.css
  src/pages/introduce/IntroducePage.js
  src/pages/main/components/MainPage.js
  src/pages/main/styles/MainCalender.css
  src/pages/main/styles/MainNotice.css
  src/pages/organization/OrganizationPage.js
  src/pages/organization/api/OrganizationAPI.js
  src/pages/organization/components/OrganizationBox.js
  src/pages/organization/components/OrganizationPage.js
  src/pages/organization/styles/OrganizationBox.css
  src/pages/organization/styles/OrganizationPage.css
  src/pages/organization/utils/OrganizationUtils.js
Labels: enhancement

#23 Feature/feat
  src/App.js
  src/common/components/Link.js
  src/common/components/Navbar.js
  src/common/constant/Navbar.js
  src/common/styles/Header.css
  src/pages/accountBook/AccountBookDetailPage/components/AccountBookDetailPage.js
  src/pages/accountBook/AccountBookPage/components/AccountBookCard.js
  src/pages/accountBook/AccountBookPage/components/AccountBookPage.js
  src/pages/activity/ActivityUploadPage/components/ActivityUploadPage.js
  src/pages/activity/ActivityUploadPage/styles/ActivityUploadPage.css
  src/pages/assignment/AssignmentDetailPage/components/AssignmentDetailPage.js
  src/pages/assignment/AssignmentPage/components/AssignmentCard.js
  src/pages/assignment/AssignmentPage/components/AssignmentPage.js
  src/pages/development/DevelopmentFormPage.js
  src/pages/development/DevelopmentUploadPage.js
  src/pages/notice/NoticeDetailPage/components/NoticeDetailPage.js
  src/pages/notice/NoticeDetailPage/styles/NoticeDetailPage.css
  src/pages/notice/NoticeFormPage/components/NoticeUploadModal.js
  src/pages/notice/NoticeFormPage/components/NoticeUploadPage.js
  src/pages/notice/NoticeFormPage/styles/NoticeUploadModal.css
  src/pages/notice/NoticeFormPage/styles/NoticeUploadPage.css
  src/pages/organization/components/OrganizationPage.js
  src/pages/regulation/components/RegulationPage.js
Labels: enhancement

#24 Feature/style
  src/common/components/FormWriteBox.js
  src/common/styles/ContentsFrame.css
  src/common/styles/Layout.css
  src/common/styles/Title.css
  src/pages/accountBook/AccountBookPage/styles/AccountBookCard.css
  src/pages/activity/ActivityDetailPage/styles/ActivityDetailPage.css
  src/pages/activity/ActivityPage/components/ActivityCard.js
  src/pages/activity/ActivityPage/components/ActivityFrame.js
  src/pages/activity/ActivityPage/styles/ActivityCard.css
  src/pages/activity/ActivityPage/styles/ActivityFrame.css
  src/pages/assignment/AssignmentPage/styles/AssignmentCard.css
  src/pages/notice/NoticePage/styles/NoticeCard.css
Labels: enhancement

#25 feat(AssignmentUploadPage.js) 과제 공지 업로드 페이지 및 모달 구현
  src/common/components/Title.js
  src/pages/accountBook/AccountBookUploadPage/components/AccountBookUploadModal.js
  src/pages/accountBook/AccountBookUploadPage/components/AccountBookUploadPage.js
  src/pages/accountBook/AccountBookUploadPage/styles/AccountBookUploadModal.css
  src/pages/accountBook/AccountBookUploadPage/styles/AccountBookUploadPage.css
  src/pages/assignment/AssignmentUploadPage/components/AssignmentUploadModal.js
  src/pages/assignment/AssignmentUploadPage/components/AssignmentUploadPage.js
  src/pages/assignment/AssignmentUploadPage/styles/AssignmentUploadModal.css
  src/pages/assignment/AssignmentUploadPage/styles/AssignmentUploadPage.css
  src/pages/assignment/constant/trackData.js
  src/pages/notice/NoticeFormPage/components/NoticeUploadModal.js
  src/pages/notice/NoticeFormPage/components/NoticeUploadPage.js
  src/pages/notice/NoticeFormPage/styles/NoticeUploadPage.css
Labels: enhancement

#26 feat (LoginAPI): 로그인 통신 구현 및 로그인 관련 로직 수정
  src/common/components/Header.js
  src/common/styles/Header.css
  src/common/utils/LogoutUtils.js
  src/pages/login/api/LoginAPI.js
  src/pages/login/components/LoginForm.js
  src/pages/login/styles/LoginForm.css
Labels: enhancement

#27 feat (MyPage): 마이페이지 구현
  src/common/constant/Title.js
  src/pages/my/MyPage.js
  src/pages/my/api/MyAPI.js
  src/pages/my/components/MyPage.js
  src/pages/my/components/MyPasswordModal.js
  src/pages/my/components/MyProfile.js
  src/pages/my/components/MyProjects.js
  src/pages/my/components/MyReadme.js
  src/pages/my/components/MyTechnology.js
  src/pages/my/components/MyTechnologyModal.js
  src/pages/my/constant/Technologies.js
  src/pages/my/styles/MyPage.css
  src/pages/my/styles/MyPasswordModal.css
  src/pages/my/styles/MyProfile.css
  src/pages/my/styles/MyProjects.css
  src/pages/my/styles/MyReadme.css
  src/pages/my/styles/MyTechnology.css
  src/pages/my/styles/MyTechnologyModal.css
  src/pages/my/utils/MyUtils.js
Labels: enhancement

#30 feat (MyPasswordModal): 비밀번호 수정 모달 구현
  src/pages/login/api/LoginAPI.js
  src/pages/my/components/MyPasswordModal.js
  src/pages/my/components/UpdatePasswordModal.js
  src/pages/my/styles/MyPasswordModal.css
  src/pages/my/styles/UpdatePasswordModal.css
  src/pages/my/utils/MyPasswordUtils.js
Labels: 🎯 feat

#31 fix: 자잘한 오류 수정
  src/App.js
  src/common/styles/Modal.css
  src/pages/main/components/MainNotice.js
  src/pages/main/styles/MainNotice.css
Labels: 🔨 fix

#33 chore: 자잘한 코드 수정
  src/pages/my/api/MyAPI.js
  src/pages/my/components/MyPage.js
  src/pages/my/components/MyProfile.js
  src/pages/my/components/MyTechnology.js
  src/pages/my/constant/Technologies.js
Labels: ✏️ chore
